# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "alankyle's blog"
weight = 1

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "Alan 个人博客"
weight = 2
